#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this ("swc", "dc", or "lc)?
carpentry: "swc"

# Overall title for pages.
title: "Microbial Genomics course 2022"

# Contact email address.
email: "mailto:al.zomer@uu.nl"

#------------------------------------------------------------
# Constant URL addresses across lessons
#------------------------------------------------------------
#
# Sites.

# Surveys.


#------------------------------------------------------------
# Lesson Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am)
start_time: 540

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

#------------------------------------------------------------
# Jekyll Generic settings (should not need to change).
#------------------------------------------------------------

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn on built-in syntax highlighting.
highlighter: rouge
